### ISSUE TITLE
claude api 请求出现 504 问题

### ISSUE THREAD

**Issue by UNICKCHENG** [UNICKCHENG/openai-proxy#10]
version: 0.3.0

![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/85da4e1a-dc19-4af8-945b-31ebef5664c0)

**Comment by UNICKCHENG** [comment]
错误原因： 超过 vercel 免费额度的最高请求时间 10 秒
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/55e94a36-6a1c-4573-9050-b207bc759f21)

**Comment by crisqyxw** [comment]
我刚才测试了一下，Netlify是应该不限制请求时长的，可以考虑部署在Netlify上？

**Comment by UNICKCHENG** [comment]
> 我刚才测试了一下，Netlify是应该不限制请求时长的，可以考虑部署在Netlify上？
> 
> ![图片](https://github.com/UNICKCHENG/openai-proxy/assets/50252868/da21f858-cdc9-4141-846e-d1c3e077dd5d)
> 
> 

嗯嗯，Netlify 确实是可以的👍 但是我没有 CDN，国内请求还需要额外配置代理。我再去找找其它 serverless 方案
