### ISSUE TITLE
Claude API返回空值

### ISSUE THREAD

**Issue by crisqyxw** [UNICKCHENG/openai-proxy#16]
![Screenshot_20230718_212113](https://github.com/UNICKCHENG/openai-proxy/assets/50252868/289c93d9-63e4-488c-ab3e-c66379a96794)
按照文档填写了organization_uuid和conversation_uuid，在Auth页面写了SessionKey，发送请求后200通过，但是返回是空值

而Claude 2的页面上显示本条消息确实已经发送出去了，Claude也响应了。
![Screenshot_20230718_212134](https://github.com/UNICKCHENG/openai-proxy/assets/50252868/9611de80-66de-47fc-b78a-88193e082f68)

**Comment by UNICKCHENG** [comment]
> ![Screenshot_20230718_212113](https://user-images.githubusercontent.com/50252868/254276478-289c93d9-63e4-488c-ab3e-c66379a96794.png) 按照文档填写了organization_uuid和conversation_uuid，在Auth页面写了SessionKey，发送请求后200通过，但是返回是空值
> 
> 而Claude 2的页面上显示本条消息确实已经发送出去了，Claude也响应了。 ![Screenshot_20230718_212134](https://user-images.githubusercontent.com/50252868/254276992-9611de80-66de-47fc-b78a-88193e082f68.png)

确实，这是因为 vercel 平台免费额度支持最长请求时间为 10 秒 左右。简单来说是，消息发送到了 Claude Web，但是在接收 claude 生成的内容时中断了，导致返回了空值或者 504（https://github.com/UNICKCHENG/openai-proxy/issues/10）

**Comment by crisqyxw** [comment]
> ![Screenshot_20230718_212113](https://user-images.githubusercontent.com/50252868/254276478-289c93d9-63e4-488c-ab3e-c66379a96794.png) 按照文档填写了organization_uuid和conversation_uuid，在Auth页面写了SessionKey，发送请求后200通过，但是返回是空值
> 
> 而Claude 2的页面上显示本条消息确实已经发送出去了，Claude也响应了。 ![Screenshot_20230718_212134](https://user-images.githubusercontent.com/50252868/254276992-9611de80-66de-47fc-b78a-88193e082f68.png)

原来如此，我看另外一条issue是返回504,没想到空值也是这个原因。
