### ISSUE TITLE
conversation_uuid 如何获取？

### ISSUE THREAD

**Issue by surfboy2000** [UNICKCHENG/openai-proxy#20]
已经支持类似 gpt 的请求格式，如果你使用的第三方插件支持自定义 OpenAI 地址，现在可以直接将 https://api.openai.com 替换成 http://openai.aihey.cc/claude/{organization_uuid}/{conversation_uuid}

conversation_uuid 如何获取？

**Comment by UNICKCHENG** [comment]
@surfboy2000 用这个接口获取
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/4b785dce-0cc7-4645-a748-ec7549ff5a98)
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/659bbbe0-cf73-4300-b272-233588ac8fc2)

**Comment by surfboy2000** [comment]
<img width="1019" alt="image" src="https://github.com/UNICKCHENG/openai-proxy/assets/52144375/017b4afc-3801-4326-9601-9eda92a2098d">

**Comment by surfboy2000** [comment]
@

> @surfboy2000 用这个接口获取 ![image](https://user-images.githubusercontent.com/32270702/255571764-4b785dce-0cc7-4645-a748-ec7549ff5a98.png) ![image](https://user-images.githubusercontent.com/32270702/255571894-659bbbe0-cf73-4300-b272-233588ac8fc2.png)

不知道哪里参数配置不对，还是报错，如上图所示

**Comment by UNICKCHENG** [comment]
> <img alt="image" width="1019" src="https://user-images.githubusercontent.com/52144375/255763131-017b4afc-3801-4326-9601-9eda92a2098d.png">

@surfboy2000  很奇怪，好像 400 这个问题只会发生在 [Apifox 网页端](https://openai-proxy.apifox.cn/api-95328790)，但是我使用 Apifox 客户端又是正常的。要不再试试下面几种方式

1. 使用 [Apifox 客户端](https://apifox.com) 来进行请求

2. 使用 curl 命令进行请求

- Linux 终端
```bash
curl -X GET "https://openai.aihey.cc/claude/organizations/2c05f2d2-da0c-4b59-9198-3d0c072863b2/chat_conversations" \
-H "Accept: */*" \
-H "Content-Type: application/json" \
-H "Cookie: sessionKey=********************" 
```

- Windows Powershell 
```powershell
curl -X GET "https://openai.aihey.cc/claude/organizations/2c05f2d2-da0c-4b59-9198-3d0c072863b2/chat_conversations" `
-H "Accept: */*" `
-H "Content-Type: application/json" `
-H "Cookie: sessionKey=********************" 
```

3. 使用 vscode REST Client 插件进行请求
- 安装 REST Client 插件
- 新建 test.http 文件，内容如下
```http
GET https://openai.aihey.cc/claude/organizations/2c05f2d2-da0c-4b59-9198-3d0c072863b2/chat_conversations
Accept: */*" 
Content-Type: application/json
Cookie: sessionKey=********************" 
```

**Comment by UNICKCHENG** [comment]
> <img alt="image" width="1019" src="https://user-images.githubusercontent.com/52144375/255763131-017b4afc-3801-4326-9601-9eda92a2098d.png">

@surfboy2000  很奇怪，好像 400 这个问题只会发生在 [Apifox 网页端](https://openai-proxy.apifox.cn/api-95328790)，但是我使用 Apifox 客户端又是正常的。要不再试试下面几种方式

1. 使用 [Apifox 客户端](https://apifox.com) 来进行请求

2. 使用 curl 命令进行请求

- Linux 终端
```bash
curl -X GET "https://openai.aihey.cc/claude/organizations/******************************/chat_conversations" \
-H "Accept: */*" \
-H "Content-Type: application/json" \
-H "Cookie: sessionKey=********************" 
```

- Windows Powershell 
```powershell
curl -X GET "https://openai.aihey.cc/claude/organizations/******************************/chat_conversations" `
-H "Accept: */*" `
-H "Content-Type: application/json" `
-H "Cookie: sessionKey=********************" 
```

3. 使用 vscode REST Client 插件进行请求
- 安装 REST Client 插件
- 新建 test.http 文件，内容如下
```http
GET https://openai.aihey.cc/claude/organizations/******************************/chat_conversations
Accept: */*" 
Content-Type: application/json
Cookie: sessionKey=********************" 
```

**Comment by surfboy2000** [comment]
> > <img alt="image" width="1019" src="https://user-images.githubusercontent.com/52144375/255763131-017b4afc-3801-4326-9601-9eda92a2098d.png">
> 
> @surfboy2000 很奇怪，好像 400 这个问题只会发生在 [Apifox 网页端](https://openai-proxy.apifox.cn/api-95328790)，但是我使用 Apifox 客户端又是正常的。要不再试试下面几种方式
> 
> 1. 使用 [Apifox 客户端](https://apifox.com) 来进行请求
> 2. 使用 curl 命令进行请求
> 
> * Linux 终端
> 
> ```shell
> curl -X GET "https://openai.aihey.cc/claude/organizations/******************************/chat_conversations" \
> -H "Accept: */*" \
> -H "Content-Type: application/json" \
> -H "Cookie: sessionKey=********************" 
> ```
> 
> * Windows Powershell
> 
> ```powershell
> curl -X GET "https://openai.aihey.cc/claude/organizations/******************************/chat_conversations" `
> -H "Accept: */*" `
> -H "Content-Type: application/json" `
> -H "Cookie: sessionKey=********************" 
> ```
> 
> 3. 使用 vscode REST Client 插件进行请求
> 
> * 安装 REST Client 插件
> * 新建 test.http 文件，内容如下
> 
> ```httpspec
> GET https://openai.aihey.cc/claude/organizations/******************************/chat_conversations
> Accept: */*" 
> Content-Type: application/json
> Cookie: sessionKey=********************" 
> ```
采用Linux 的命令方式，获取到uuid。但是有2个，选后者。还是任意
<img width="497" alt="image" src="https://github.com/UNICKCHENG/openai-proxy/assets/52144375/089ca581-6940-491f-bd85-257c5606e803">

**Comment by surfboy2000** [comment]
Also, actually I want to replace openai with claude. If api_proxy is replaced, then open_api_key is replaced by SessionKey. So do keywords （open_api_key）still need to be replaced?

**Comment by UNICKCHENG** [comment]
除了 organization_uuid 和 conversation_uuid 两个路径参数外，你还需要将 token 替换为你的 sessionKey。之后，你可以将 OpenAI Base (https://api.openai.com) 替换成 `https://openai.aihey.cc/claude/{organization_uuid}/{conversation_uuid}` 来使用。

![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/568397ce-3111-4c21-a16c-20559833955b)


> Also, actually I want to replace openai with claude. If api_proxy is replaced, then open_api_key is replaced by SessionKey. So do keywords （open_api_key）still need to be replaced?另外，实际上我想用claude代替openai。如果API_proxy被替换，那么open_api_key被SessionKey替换。那么关键字（open_API_key）还需要替换吗？
