### ISSUE TITLE
无法响应OPTIONS请求

### ISSUE THREAD

**Issue by mzbgf** [UNICKCHENG/openai-proxy#28]
对于OPTIONS请求，总是返回405
浏览器无法跨站请求

**Comment by UNICKCHENG** [comment]
@mzbgf  请使用确定的 method，如 GET、POST、DELETE，而不是 OPTIONS

**Comment by mzbgf** [comment]
> @mzbgf 请使用确定的 method，如 GET、POST、DELETE，而不是 OPTIONS

options是一种浏览器级行为，是因为在某些情况下，普通的get或者post请求回首先自动发起一次options请求，当options请求成功返回后，真正的ajax请求才会再次发起。
--来自互联网

**Comment by UNICKCHENG** [comment]
我没太理解，所以你的问题是？？？

**Comment by mzbgf** [comment]
> 我没太理解，所以你的问题是？？？

使用浏览器控制台运行这段代码

const url = `https://openai-proxy.coolc.life/claude/${organization_uuid}/v1/chat/completions`;

const headers = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${OPENAI_API_KEY}`
};

const body = {
  model: 'gpt-3.5-turbo',
  messages: [{role: 'user', content: 'Say this is a test!'}],
  temperature: 0.7  
};

fetch(url, {
  method: 'POST',
  headers: headers,
  body: JSON.stringify(body)  
})
.then(res => res.json()) 
.then(data => console.log(data))
.catch(err => console.error(err));

**Comment by UNICKCHENG** [comment]
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/707ec3f3-77a3-4a19-9d01-0bb773790cc8)


> > 我没太理解，所以你的问题是？？？
> 
> 使用浏览器控制台运行这段代码
> 
> ```
> const url = `https://openai-proxy.coolc.life/claude/${organization_uuid}/v1/chat/completions`;
> 
> const headers = {
>   'Content-Type': 'application/json',
>   'Authorization': `Bearer ${OPENAI_API_KEY}`
> };
> 
> const body = {
>   model: 'gpt-3.5-turbo',
>   messages: [{role: 'user', content: 'Say this is a test!'}],
>   temperature: 0.7  
> };
> 
> fetch(url, {
>   method: 'POST',
>   headers: headers,
>   body: JSON.stringify(body)  
> })
> .then(res => res.json()) 
> .then(data => console.log(data))
> .catch(err => console.error(err));
> ```

**Comment by mzbgf** [comment]
跨域才会报错，在别的网站里调用你这个api会报错，你打开别的网站再打开控制台才看的到

**Comment by mzbgf** [comment]
> ![image](https://user-images.githubusercontent.com/32270702/257061274-707ec3f3-77a3-4a19-9d01-0bb773790cc8.png)
> 
> > > 我没太理解，所以你的问题是？？？
> > 
> > 
> > 使用浏览器控制台运行这段代码
> > ```
> > const url = `https://openai-proxy.coolc.life/claude/${organization_uuid}/v1/chat/completions`;
> > 
> > const headers = {
> >   'Content-Type': 'application/json',
> >   'Authorization': `Bearer ${OPENAI_API_KEY}`
> > };
> > 
> > const body = {
> >   model: 'gpt-3.5-turbo',
> >   messages: [{role: 'user', content: 'Say this is a test!'}],
> >   temperature: 0.7  
> > };
> > 
> > fetch(url, {
> >   method: 'POST',
> >   headers: headers,
> >   body: JSON.stringify(body)  
> > })
> > .then(res => res.json()) 
> > .then(data => console.log(data))
> > .catch(err => console.error(err));
> > ```

跨域才会报错，在别的网站里调用你这个api会报错，你打开别的网站再打开控制台才看的到

**Comment by UNICKCHENG** [comment]
确实，之前没考虑这个问题，我去研究研究

**Comment by UNICKCHENG** [comment]
@mzbgf 再试一试？
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/43062b80-520f-4e69-b9aa-03a9c6865f9f)

**Comment by mzbgf** [comment]
可以了，谢谢
