### ISSUE TITLE
错误反馈: 部署在chatgpt next web,经常出现断流，或者直接显示An error occurred with your deployment  FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by ychappyboy** [UNICKCHENG/openai-proxy#33]
刚部署完使用没有问题，但很快就出现了断流问题，回复问题不完整，后来频繁出现An error occurred with your deployment FUNCTION_INVOCATION_TIMEOUT提示，请大神帮忙看一下，谢谢！

**Comment by UNICKCHENG** [comment]
@ychappyboy  好像是函数请求超时了，你是自建的么，可以试一试将函数执行时间设置长一点

![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/7615050b-d912-42e0-89b6-b2e3b12b1594)

**Comment by ychappyboy** [comment]
> @ychappyboy 好像是函数请求超时了，你是自建的么，可以试一试将函数执行时间设置长一点
> 
> ![image](https://user-images.githubusercontent.com/32270702/258962446-7615050b-d912-42e0-89b6-b2e3b12b1594.png)

我用的chatgpt next web部署的，没找到函数执行时间的设置呢

**Comment by UNICKCHENG** [comment]
@ychappyboy  openai-proxy 是自建的么？

**Comment by ychappyboy** [comment]
> @ychappyboy openai-proxy 是自建的么？

是啊

**Comment by UNICKCHENG** [comment]
vercel 是付费版么？免费版有执行时间限制，容易触发超时，可以参考 https://github.com/UNICKCHENG/openai-proxy/issues/10

> > @ychappyboy openai-proxy 是自建的么？
> 
> 是啊，fork代码后用vercel部署的

**Comment by ychappyboy** [comment]
> vercel 是付费版么？免费版有执行时间限制，容易触发超时，可以参考 #10
> 
> > > @ychappyboy openai-proxy 是自建的么？
> > 
> > 
> > 是啊，fork代码后用vercel部署的

明白了，谢谢大神，那可以部署在cloudeflare上吗，现在部署在cloudflare上的代理用官方的claude api没出现过断流呢
