### ISSUE TITLE
我自己部署了的docker，是不是调用本机的13000就可以了？

### ISSUE THREAD

**Issue by howie-cn** [UNICKCHENG/openai-proxy#37]
我服务器ip是米国地址，安装了成功了docker，但是打开 http://localhost:13000 跳转到博主这里github来了（https://github.com/UNICKCHENG/openai-proxy）

我想问的是，  的的本机作为post_url, "http://localhost:13000/claude/organizations/dca2a902-a463-41f0-88cb-b047deb40178/chat_conversations"  这种是可以的吧？
不然我自己部署就没啥意义了
谢谢博主

**Comment by UNICKCHENG** [comment]
> 我服务器ip是米国地址，安装了成功了docker，但是打开 http://localhost:13000 跳转到博主这里github来了（[https://github.com/UNICKCHENG/openai-proxy）](https://github.com/UNICKCHENG/openai-proxy%EF%BC%89)
> 
> 我想问的是， 的的本机作为post_url, "http://localhost:13000/claude/organizations/dca2a902-a463-41f0-88cb-b047deb40178/chat_conversations" 这种是可以的吧？ 不然我自己部署就没啥意义了 谢谢博主

嗯嗯，把 `https://openai.aihey.cc` 换成你自建的地址就好啦，也就是 `http://localhost:13000`
