### ISSUE TITLE
举个爪: 没太理解在vercel中自建的话解决的是什么问题？

### ISSUE THREAD

**Issue by xiaobai3310** [UNICKCHENG/openai-proxy#39]
### 你的困惑是什么

大佬可以普及下，在vercel自建的话解决的是什么问题啊？以及是怎么解决这个问题的呢？我看还是要填openai.aihey.cc这个域名进去

### 你有做过哪些尝试

先学习

### 你希望我怎么帮你

解释

**Comment by UNICKCHENG** [comment]
@xiaobai3310  因为使用 vercel，也就意味着可以部署在海外服务器上，一些 IP 限制也就解决了

- claude web api 地区 ip 限制
- google bard web api 地区 ip 限制

如果你使用 vercel 自建的话，vercel 会生成一个地址，如果你想自定义域名，可以参考 readme.md 中的截图进行配置，openai.aihey.cc 只是一个样例，填写你自己的就好

注意 vercel 免费有执行时间的限制，claude web api 可能会失败 ，可以参考 https://github.com/UNICKCHENG/openai-proxy/issues/10

**Comment by xiaobai3310** [comment]
> @xiaobai3310 因为使用 vercel，也就意味着可以部署在海外服务器上，一些 IP 限制也就解决了
> 
> * claude web api 地区 ip 限制
> * google bard web api 地区 ip 限制
> 
> 如果你使用 vercel 自建的话，vercel 会生成一个地址，如果你想自定义域名，可以参考 readme.md 中的截图进行配置，openai.aihey.cc 只是一个样例，填写你自己的就好
> 
> 注意 vercel 免费有执行时间的限制，claude web api 可能会失败 ，可以参考 #10

3q
