### ISSUE TITLE
举个爪: 作者你好, 我想问下你这个项目的原理是什么

### ISSUE THREAD

**Issue by Marx2014** [UNICKCHENG/openai-proxy#46]
### 你的困惑是什么

我想问下你这个项目的原理是什么, 是怎么过claude2国家限制的?

### 你有做过哪些尝试

我尝试用 js 写一个简单的 claude2  api转发, 像这样
```
module.exports = async (req: VercelRequest, res: VercelResponse) => {
        const response = await fetch(`https://claude.ai/api/organizations/${user}/chat_conversations`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify({uuid: uuid, name: 'test'})
        });
        const data = await response.text();
        res.status(200).send(data);
}
```
我在本地开启美国ip的vpn的环境下 开发了以上代码, 并测试成功返回 uuid会话创建成功的json,   于是我把以上代码部署vercel 中执行,  返回了乱码, 研究很久发现不是编码问题, 我打印了一下resp.url ,返回了一条' 不支持该国家和地区' 的url

机缘巧合下, 我找到了你的项目, 我尝试部署你的项目到vercel中,  结果你的代码可以访问并正常返回json 为什么?

本人不懂js 和服务器之类的原理 (我是个移动端的哈哈哈), 我简单查阅了你的代码,发现好像没做什么特殊的处理, 好像是因为 middleware  中间件?  做了一些跨域转发操作?  

### 你希望我怎么帮你

希望能解答一下我以上的疑问

**Comment by UNICKCHENG** [comment]
@Marx2014  试试重写 headers，参考 [createConversation](https://github.com/UNICKCHENG/openai-proxy/blob/7a0b0e6683b592968200b5bdca5e082f973fe0dd/libs/claude/conversation.ts#L54C1-L58C11)。因为 headers 会包含你的 ip 等信息

**Comment by Marx2014** [comment]
headers 我已经是用自定义的了, 可是还是一样的,  要么返回 
 "{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}"
 要么直接返回 不支持的区域
 
 我的请求头是这样的
```
         const headers = {
            'Authority': 'claude.ai',
            'Scheme': 'https',
            'Accept': '*/*',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'en-US,en;q=0.5',
            'Content-Type': 'application/json',
            'Cookie': cookies,
            'Origin': 'https://claude.ai',
            'Referer': 'https://claude.ai/chats',
            'Sec-Ch-Ua': '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
            'Sec-Ch-Ua-Mobile': '?0',
            'Sec-Ch-Ua-Platform': '"Windows"',
            'Sec-Fetch-Dest': 'empty',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
        };

```



我用fetch 获取www.google.com的html代码 是可以访问的, 说明是可以访问外网的,  


太奇怪了

**Comment by UNICKCHENG** [comment]
试一试这个写法呢？

```typescript
const ORG_UUID=*************
const SESSION_KEY=**********

fetch(`https://claude.ai/api/organizations/${ORG_UUID}/chat_conversations`, {
  method: 'GET',
  headers: {
    'Accept': 'application/json',
    'Cookie': `sessionKey=${SESSION_KEY}`,
  },
})
.then(res => res.json())
.then(res => console.log(res))
.catch(err => console.log(err))
```

**Comment by Marx2014** [comment]
谢谢作者！我已经解决了。我换成了与你相同的Next.js环境，重新复制粘贴了以上的fetch请求，并进行了测试。终于不再提示地区限制或权限错误了。我之前是用Node.js实现的，一直给我提示错误。虽然我不太理解Next.js和Node.js的区别，但还是非常感谢作者。这个问题让我头疼了好几天，一直无法解决...
