### ISSUE TITLE
错误反馈:  Claude Web API 暂时不可用

### ISSUE THREAD

**Issue by li904775857** [UNICKCHENG/openai-proxy#57]
### 能告诉我发生了什么么？What happened?

按照文档去网页获取和指定的sessionKey 和 organization_uuid 后，去配置测试请求，发现返回数据为空

![image](https://github.com/UNICKCHENG/openai-proxy/assets/43633294/464b6f19-bfc3-4b43-a2b5-f5e4644cfd9b)

麻烦看下是什么情况

**Comment by mapxn** [comment]
据说Claude在8月16日更新了SDK

**Comment by UNICKCHENG** [comment]
是的，也许 Claude Web 增加了安全机制

Here you can see the same problem: https://github.com/KoushikNavuluri/Claude-API/issues/42

**Comment by zyh94946** [comment]
> 是的，也许 Claude Web 增加了安全机制
> 
> Here you can see the same problem: [KoushikNavuluri/Claude-API#42](https://github.com/KoushikNavuluri/Claude-API/issues/42)

这个已经修复了，看样子是增加了浏览器模拟，可以跟进吗

**Comment by UNICKCHENG** [comment]
> > 是的，也许 Claude Web 增加了安全机制
> 
> > 
> 
> > Here you can see the same problem: [KoushikNavuluri/Claude-API#42](https://github.com/KoushikNavuluri/Claude-API/issues/42)
> 
> 
> 
> 这个已经修复了，看样子是增加了浏览器模拟，可以跟进吗

嗯嗯，正在跟进ing

**Comment by howie-cn** [comment]
> 

加油，突然没法用了~

**Comment by UNICKCHENG** [comment]
@li904775857 @llv5 @mapxn @zyh94946 @howie-cn 应该修复了，试一试？

**Comment by howie-cn** [comment]
![image](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/97ebd3bc-581e-43c4-a99f-82f118eb25c5)

![image](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/5aa510c0-2e95-416a-b0a3-ba0ab2056827)

![image](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/f51637f5-705a-410b-9891-fb1711c453a2)

博主好，我试用了下新的claude接口， 提交后，在claude的主网页是有相关信息的，但是相关回复response 没有反馈到程序端来，程序端的output报错

**Comment by howie-cn** [comment]
![2](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/312c7d24-3d89-49f0-a7c4-2675822937e8)
![3](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/55c45925-d68b-4690-a2dd-4503d4f5d0df)
![1](https://github.com/UNICKCHENG/openai-proxy/assets/30275483/46aa263c-687f-450c-a336-e7e375d753cf)
博主好，我试用了下新的claude接口， 提交后，在claude的主网页是有相关信息的，但是相关回复response 没有反馈到程序端来，程序端的output报错
