### ISSUE TITLE
举个爪: claude web api似乎不稳定

### ISSUE THREAD

**Issue by flewsea** [UNICKCHENG/openai-proxy#66]
### 你的困惑是什么

当问题稍微复杂一些，返回结果就不可用，有时候是504错误。比如提问：介绍下自己/你知道ts么。  此时可以正常返回内容。
![image](https://github.com/UNICKCHENG/openai-proxy/assets/4075883/06a64cf4-4a9c-496b-bd3a-a5f4ef800ff0)

提问：介绍一下typescript。时间会变得非常长，最终结果也是失败
![image](https://github.com/UNICKCHENG/openai-proxy/assets/4075883/19d67554-5458-466e-b71a-4dc9ea67c12e)

### 你有做过哪些尝试

尝试使用docker 在云服务器上自建了一个代理服务，但是问题依旧

### 你希望我怎么帮你

希望帮忙确认下问题的原因

**Comment by UNICKCHENG** [comment]
@flewsea  应该修复了，再试试？
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/87ee4019-f7e0-4676-92aa-67164f479d8f)

**Comment by flewsea** [comment]
测试没有问题了，谢谢作者。
